name: record_api
description: Example uses of record APIs for documentation purposes.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.6.1
resolution: workspace

dependencies:
  trailbase:
    path: ../../../client/dart

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
