name: test

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      TRAIL_ENABLE_RECORD_TRANSACTIONS: true
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install Dependencies
        run: |
          sudo apt-get update && \
            sudo apt-get install -y --no-install-recommends curl libssl-dev pkg-config libclang-dev protobuf-compiler libprotobuf-dev
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Poetry and Python Dependencies
        run: |
          pipx install --python python3.13 "poetry==2.1.3" && poetry -C client/python install
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: PNPM install
        run: |
          pnpm i
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.5
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      # - name: Setup Go
      #   uses: actions/setup-go@v5
      #   with:
      #     go-version: "1.24.x"
      # Swift 6.1 is preinstalled and swift-action sporadically fails on
      # gpg issues: https://github.com/swift-actions/setup-swift/issues/694
      # - uses: swift-actions/setup-swift@v2
      #   with:
      #     swift-version: "6.1"
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: "--all-files --verbose"
